 drop table if exists doctor CASCADE;
 drop table if exists patient CASCADE;
 drop table if exists receipt CASCADE;


 create table doctor (doctor_id bigint generated by default as identity, name varchar(255), primary key (doctor_id));
 create table patient (id bigint generated by default as identity, age integer not null, name varchar(255), doctor_id bigint, receipt_id bigint, primary key (id));
 create table receipt (id bigint generated by default as identity, name varchar(255), price integer not null, primary key (id));

 alter table patient add constraint FKmer5utvy1hiff7ovs6f4bjtnw foreign key (doctor_id) references doctor;
 alter table patient add constraint FKlgoa2ekvy6ws7h7dn7q1u8942 foreign key (receipt_id) references receipt;